version: "3.8"

services:
  web:
    container_name: nuxt
    depends_on:
      - api
    build: "./pomodoro-frontend"
    ports:
      - 3000:3000

  api:
    container_name: adonis
    depends_on:
      - db
      - cache
    build: "./pomodoro-backend"
    ports:
      - 3333:3333

  db:
    container_name: mysql
    image: mysql
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  cache:
    container_name: redis
    image: redis:6-alpine
    ports:
      - 6379:6379

volumes:
  mysql_volume:
