version: "3.8"

services:
  db:
    container_name: mysql
    image: mysql
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./dockerConfig/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  cache:
    container_name: redis
    image: redis:6-alpine
    ports:
      - 6379:6379

  web:
    container_name: nuxt
    image: timothyryeyn/pomodoro-frontend:1.0
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - API_PORT=http://3.104.95.254:3333/api
    depends_on:
      - api
    ports:
      - 80:3000

  api:
    container_name: adonis
    image: timothyryeyn/pomodoro-backend:1.0
    environment:
      - HOST=0.0.0.0
      - APP_KEY=8xlaZqIc72Bm_C-mQdveVtNJHsPtK0aV
      - DRIVE_DISK=local
      - DB_CONNECTION=mysql
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB_NAME=pomodoro
      - REDIS_CONNECTION=local
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    depends_on:
      - db
      - cache
    ports:
      - 3333:3333

volumes:
  mysql_volume:
